### ISSUE TITLE
fix: unable to create reports

### ISSUE THREAD

**Issue by orellano-c** [buchi-labortechnik-ag/ds-feedback#9]
### Service

cloud.io

### Version

1.10.0

### Overview

The app cannot create report (pdf) files.

### Steps to Reproduce

- Follow the workflow for cloud.io
- Try to generate a report
- The app returns an error

### Expected Behavior

The user should be able to download a report (pdf)

**Comment by ncudlenco** [comment]
In progress @NathaliaForero

**Comment by ncudlenco** [comment]
Fixed in latest version of cloud.api

**Comment by orellano-c** [comment]
LGTM, I was able to download a report 👍
